name: publish

on: [push]

jobs:
  publish-pwahub-api-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: login to github container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push pwahub-api docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm64/v8
          push: true
          tags: ghcr.io/lmarschall/foodover-rework:latest
        # run: |
        #   docker build . --tag ghcr.io/pwahub/pwahub-api:latest
        #   docker push ghcr.io/pwahub/pwahub-api:latest
